### ISSUE TITLE
master -> main branch rename (umbrella issue)

### ISSUE THREAD

**Issue by idvoretskyi** [cncf/foundation#149] opened 2021-04-14 10:22 UTC
This is an umbrella issue that tracks branch renaming from master -> main across the CNCF projects.

Ref.: https://github.com/github/renaming

**Comment by scottrigby** [comment] 2022-01-17 07:58
duplicate of #140?

**Comment by idvoretskyi** [comment] 2022-01-17 08:05
@scottrigby this is a CNCF-owned umbrella issue for the tracking purposes, but that’s for flagging.

**Closed** 2022-06-07 19:49 UTC
